project:
  type: book
  pre-render: R/hulpbestanden.R

book:
  title: "Data Analyse met Excel"
  subtitle: "Een cursusboek over het analyseren van data met Excel."
  author: "Ben Welman"
  date: today
  date-format: long
  google-analytics: "G-CMGT59LG7K"
  site-url: https://excelanalyse.netlify.app/
  repo-url: https://github.com/bwelman/excelanalyse
  repo-actions: [issue]
  chapters:
    - index.qmd
    - voorwoord.qmd
    - data-import.qmd
    - data-variabelen.qmd
    - beschrijvend.qmd
    - linregressie.qmd
    - tijdreeksen.qmd
    - prognoses.qmd
    - eda.qmd
    - cases.qmd
  appendices:
    - analysis-toolpak.qmd
    - powerquery-options.qmd
    - excel-trendlijnen.qmd
    - excel-voorspellingenblad.qmd
    - excel-aselect.qmd
    - databronnen.qmd
    - referenties.qmd

execute:
  freeze: auto

lang: nl

language:
  en:
    crossref-prp-title: "Task"
  nl:
    crossref-prp-title: "Taak"

format:
  html:
    include-after-body: include/webex-nl.js
    css: include/webex.css
    theme:
      - cosmo
      - include/textbook.scss
    cover-image: images/cover.png
    fig-width: 6
    fig-asp: 0.618
    code-fold: false
    link-external-icon: true
    link-external-newwindow: true
    callout-appearance: simple
    author-meta: "Ben Welman"
    description-meta: "Leer aan de hand van dit studieboek hoe je inzicht in gegevens kunt krijgen door de data te analyseren met Excel."
    keywords: ["Excel", "Power Query", "exploratieve data analyse", "gegevensanalyse", "studieboek", "cursusboek", "statistiek", "tijdreeksen", "regressie", "voorspellingen"]

  # pdf:
  #   documentclass: scrbook
  #   papersize: a4
  #   include-in-header: latex/preamble.tex
  #   links-as-notes: true

knitr:
  opts_chunk:
    echo: false
    warning: false
    message: false
    cache: false
