# Databronnen {#sec-databronnen}

## Landen {.unnumbered}

**Nederland**

-   [CBS (Centraal Bureau voor de Statistiek)](https://www.cbs.nl/)
    - [StatLine](https://opendata.cbs.nl/statline/#/CBS/nl/)
-   [Dataregister van de Nederlandse Overheid](https://data.overheid.nl/) : Nationaal dataportaal Nederlandse overheid. Bevat datasets in veel domeinen (zorg, energie, verkeer, ...) en een zoekoptie.
-   [Open data Tweede Kamer](https://opendata.tweedekamer.nl) : Open Data Portaal voor o.a. wetsvoorstellen, moties, amendementen, verslagen en de samenstelling van fracties en commissies.
-   [DANS](https://dans.knaw.nl/nl/) : Nationaal expertisecentrum en repository voor onderzoeksdata.
-   [Open data van de Nederlandse Zorgautoriteit](https://www.opendisdata.nl/) : Zorg- en behandeldata van Nederlandse ziekenhuizen.
-   [Compendium voor de Leefomgeving](https://www.clo.nl/) : Website met feiten en cijfers over milieu, natuur en ruimte in Nederland. Veel bijbehorende datasets kunnen gedownload worden.

**Europa**

-   [Eurostat (Europees Bureau voor de Statistiek)](https://ec.europa.eu/eurostat/web/main/home) : Statistische bureau van de Europese Unie.
-   [EEA (European Environment Agency)](https://www.eea.europa.eu/data-and-maps) : Europees Milieuagentschap, met data over het milieu.
-   [data.europe.eu](https://data.europa.eu/nl) : Het officiële portaal voor Europese data.

**UK**

-   [Office for National Statistics](https://www.ons.gov.uk/)
-   [Data.GOV.UK](https://data.gov.uk/) : Open dataportaal voor gepubliceerde gegevens van overheidsinstanties.

**Verenigde Staten**

-   [Data.Gov](https://www.data.gov/) : De thuisbasis van de open data van de Amerikaanse overheid.
-   [FRED (Federal Reserve Bank of ST. Louis)](https://fred.stlouisfed.org/) : Economische data, tijdreeksen, veel zoekmogelijkheden.
-   [GSS (General Social Surveau)](http://gss.norc.org/) : Voert sociologische onderzoeken uit en verzamelt gegevens over de zorgen, ervaringen en gewoontes van Amerikaanse burgers.
-   [Fed](https://www.federalreserve.gov/data.htm) : Data Federal Reserve Bank

**Wereld**

-   [World Bank Open Data](https://data.worldbank.org/) : Tijdreeksgegevens over diverse onderwerpen. Je kunt je eigen query's maken.
-   [UNdata](http://data.un.org/) : Dataportaal voor het zoeken en downloaden van verschillende statistische bronnen die zijn samengesteld door het statistische systeem van de Verenigde Naties.
-   [UN World Population Prospects](https://population.un.org/wpp/) : Bevolkingsgegevens van de afdeling Economische en Sociale Zaken van de VN.
-   [Our world in Data](https://ourworldindata.org/) : Open Access arikelen over diverse onderwerpen met bijbehorende data.
-   [Penn World Table](https://www.rug.nl/ggdc/productivity/pwt/) : Een database met informatie over de relatieve niveaus van inkomen, output, input en productiviteit van 183 landen vanaf 1950.
-   [Maddison Project Database](https://www.rug.nl/ggdc/historicaldevelopment/maddison/releases/maddison-project-database-2018) : Biedt informatie over vergelijkende economische groei en inkomensniveaus op de zeer lange termijn. De 2018-versie van deze database (o.a. in Excel formaat) bestrijkt 169 landen en de periode tot 2016.
-   [Human Mortality Database (HMD)](https://www.mortality.org/) : Toonaangevende wetenschappelijke gegevensbron over sterfte en bevolking in ontwikkelde landen.

## Thema's {.unnumbered}

**Financieel**

-   [Yahoo Finance](https://finance.yahoo.com) : Bevat veel interessante financiele data (ook historische) die je kunt downloaden, zoals
    -  [AEX historische data](https://finance.yahoo.com/quote/%5EAEX/history?period1=1485817200&period2=1546210800&interval=1d&filter=history&frequency=1d)

**Medisch**

-   [NKR (Nederlandse Kanker Registratie)](http://www.cijfersoverkanker.nl/)

**Klimaat/Weer**

-   [KNMI Klimatologie](https://www.knmi.nl/nederland-nu/klimatologie) : Historische weerdata.
-   [Emissieregistratie](https://www.emissieregistratie.nl/) : Jaarlijkse emissies van alle Nederlandse bronnen. Je kunt een door jezelf samengestelde dataset downloaden in Excel formaat.
-   [IEM (Iowa Environmental Mesonet)](https://mesonet.agron.iastate.edu/request/download.phtml) : Klimaat- en weergegevens van veel plekken in de wereld (ook Nederland) <!-- Voor een toepassing zie o.a. nycflights13 project (R) -->

**Transport**

-   [openFlights.org](http://openflights.org/data.html) : Database met gegevens van meer dan 10000 vliegvelden, treinstations, veerboothavens over de hele wereld.
-   [BTS (Bureau of Transportation Statistics)](https://www.bts.gov/) : Statistieken over commerciële luchtvaart, multimodale vrachtactiviteit en transporteconomie.
-   FAA (Federal Aviation Administration) : Transportorganisatie van de Amerikaanse overheid die de burgerluchtvaart reguleert.
    -  [Data and Research](https://www.faa.gov/data_research/) : Verschillende data over vluchten.
    -  [Aircraft Registry](https://www.faa.gov/licenses_certificates/aircraft_certification/aircraft_registry/releasable_aircraft_download/) : Database met registratie van vliegtuigen. <!-- Voor een toepassing zie o.a. nycflights13 project -->

## Zoekmachines/Portalen {.unnumbered}

-   [Google Dataset Search](https://toolbox.google.com/datasetsearch) : Zoekmachine voor datasets.

-   [Find Economic Articles with Data](https://ejd.econ.mathematik.uni-ulm.de/) : Economische artikelen met data zoeken, ook zoeken op gebruikte onderzoeksmethode is mogelijk, zie ook [Uitleg](https://skranz.github.io//r/2022/04/06/FindingEconomicArticles5.html)

-   [DASL (Data And Story Library)](https://dasl.datadescription.com/) : Een archief van databestanden voor gebruik door studenten en docenten statistiek en data science voor een breed scala aan onderwerpen, met achtergrondinformatie over de data.

-   [Kaggle](https://www.kaggle.com/) : Een online communityplatform voor datawetenschappers en liefhebbers van machine learning. Je kunt er zeer veel openbare datasets en notebooks vinden. Je kunt desgewenst samenwerken met andere gebruikers en meedoen aan competities.

