# Referenties {.unnumbered}

**Excel**

-   [Leer Excel 365](https://leerexcel.netlify.app/) - Online studieboek voor het leren werken met Excel (gratis).

**Statistiek**

-   [Online cursus statistiek Universiteit van Utrecht](https://www.uu.nl/onderwijs/open-en-gepersonaliseerd-statistiekonderwijs/lesmateriaal)
-   [Dr.Stat](http://drstat.net/nl) - Cursus statistiek voor studenten in het HO (gratis).

**Tijdreeksen**

-   [Dossier Conjunctuur (CBS)](https://www.cbs.nl/nl-nl/dossier/dossier-conjunctuur)
-   [Conjunctuurklok (CBS)](https://www.cbs.nl/nl-nl/visualisaties/conjunctuurklok)

**Databronnen**

-   Nederland
    -   [CBS (Centraal Bureau voor de Statistiek)](https://www.cbs.nl/) met [StatLine](https://opendata.cbs.nl/statline/#/CBS/nl/)
    -   [Dataregister van de Nederlandse Overheid](https://data.overheid.nl/)
    -   [KNMI Klimatologie](https://www.knmi.nl/nederland-nu/klimatologie) - daggegevens van het weer
    -   [Open data van de Nederlandse Zorgautoriteit](https://www.opendisdata.nl/)
    -   [Compendium voor de Leefomgeving](https://www.clo.nl/) - Website met feiten en cijfers over milieu, natuur en ruimte in Nederland. Veel bijbehorende datasets kunnen in kunnen gedownload worden.

-   Europa
    -   [Eurostat (Europees Bureau voor de Statistiek)](https://ec.europa.eu/eurostat/web/main/home)
    -   [ESS (European Social Survey)](https://www.europeansocialsurvey.org/)
    -   [EEA (European Environment Agency)](https://www.eea.europa.eu/data-and-maps) - data over het milieu.
    -   [data.europe.eu](https://data.europa.eu/nll) - Het officiële portaal voor Europese data.

-   Verenigde Staten
    -   [Data.Gov](https://www.data.gov/) - Open data van de Amerikaanse overheid.
    -   [FRED (Federal Reserve Bank of ST. Louis)](https://fred.stlouisfed.org/) - Economische data, tijdreeksen, veel zoekmogelijkheden.
    -   [GSS (General Social Surveau)](http://gss.norc.org/) - Voert sociologische onderzoeken uit en verzamelt gegevens over de zorgen, ervaringen en gewoontes van Amerikaanse burgers.
    -   [SCF (Survey of Consumer Finances)](https://www.federalreserve.gov/scf/scf.htm) - Publiceert gegevens over gezinsbalansen, pensioenen, inkomen en de demografische kenmerken van Amerikaanse huishoudens.

-   Wereld
    -   [UNdata](http://data.un.org/) - Bevat links naar de officiele statistische bureaus van alle landen.
    -   [Population](https://population.un.org/wpp/) - Bevolkingsvooruitzichten van de afdeling Economische en Sociale Zaken van de UN.
    -   [Our world in Data](https://ourworldindata.org/) - Open Access arikelen over diverse onderwerpen met bijbehorende data.
    -   [StatSci](http://www.statsci.org) - A portal for statistical science, the discipline of statistics.
    -   [Penn World Table](https://www.rug.nl/ggdc/productivity/pwt/) - Een database met informatie over de relatieve niveaus van inkomen, output, input en productiviteit van 183 landen vanaf 1950.
    -   [Google Dataset Search](https://datasetsearch.research.google.com/) - Zoekmachine voor datasets.
